{
 "title": "Ethernet over Powerline",
 "description": "Devolo adapters ethernet over powerline statistics",
 "tags": [
  "Device",
  "devolo"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Adapter",
    "query": {
     "query": "label_values(devolo_device_info_info,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device information",
   "type": "table",
   "description": "General information about the device",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "devolo_device_info_info{hostname=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total devices",
   "type": "gauge",
   "description": "Total connected devices in network",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(devolo_connected_devices_amount)",
     "legendFormat": "Total devices"
    }
   ]
  },
  {
   "title": "PHY Speed",
   "type": "timeseries",
   "description": "Layer 1 speed between adapters in the powerline network.\n\n|Threshold|Type|\n|-|-|\n|3000 Mbps|Theoretical max speed (G.hn 2x2 MIMO)|\n|2400 Mbps|Devolo advertised max speed (Magic 2 LAN)|\n|2000 Mbps|Satisfactory real world speed (G.hn 2x2 MIMO)|\n|1500 Mbps|Theoretical max speed (G.hn SISO)|\n|1000 Mbps|Theoretical max speed (HomePlug AV2)|\n|600 Mbps|Theoretical max speed (HomePlug AV)|\n|<600Mbps|Unsatisfactory speed (G.hn)|",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "devolo_tx_rate_megabits{from_hostname=~\"$hostname\"}",
     "legendFormat": "{{from_hostname}} -> {{to_hostname}}"
    }
   ]
  },
  {
   "title": "Connected devices",
   "type": "timeseries",
   "description": "Amount of connected devices on the adapter",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "devices" } },
   "targets": [
    {
     "expr": "devolo_connected_devices_amount{hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}} connected to"
    }
   ]
  }
 ]
}